# Generated by Django 3.0.7 on 2020-12-03 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20201130_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 21, 29, 35, 194069)),
        ),
    ]
