# Generated by Django 3.0.7 on 2020-12-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20201203_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='year',
            field=models.IntegerField(),
        ),
    ]
