# Generated by Django 3.0.7 on 2020-08-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='potency',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
