# Generated by Django 3.0.7 on 2020-12-27 09:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentsCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
                ('date_str', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('eventId', models.CharField(blank=True, max_length=50, null=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='profiles.UserProfile')),
            ],
        ),
    ]
