# Generated by Django 3.0.7 on 2020-11-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(blank=True, max_length=300, null=True)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
