# Generated by Django 3.0.7 on 2020-11-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentscalendar',
            old_name='confirm',
            new_name='confirmed',
        ),
    ]
