# Generated by Django 3.0.7 on 2020-12-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentscalendar',
            name='eventId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
