# Generated by Django 3.0.7 on 2020-12-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentscalendar',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentscalendar',
            name='order_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='AppointmentDetails',
        ),
    ]
