# Generated by Django 3.0.7 on 2020-11-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='CalendarAppointments',
        ),
    ]
