# Generated by Django 3.0.7 on 2020-11-18 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20201117_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentsCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='CalendarAppointments',
        ),
    ]
