# Generated by Django 3.0.7 on 2020-11-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20201118_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentscalendar',
            old_name='date',
            new_name='start_time',
        ),
    ]
