# Generated by Django 3.0.7 on 2020-11-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20201118_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentscalendar',
            old_name='start_time',
            new_name='date',
        ),
    ]
