# Generated by Django 3.0.7 on 2020-11-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20201118_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookAppointment',
        ),
        migrations.AddField(
            model_name='appointmentscalendar',
            name='date_str',
            field=models.CharField(default='01/12/2020', max_length=10),
            preserve_default=False,
        ),
    ]
