# Generated by Django 3.0.7 on 2020-11-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20201120_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentscalendar',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
