# Generated by Django 3.0.7 on 2020-11-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_purchaseappointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseAppointment',
        ),
    ]
